config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get '/callback', to: 'oauth#callback'
  get '/authorize', to: 'oauth#authorize'
  get '/deauthorize', to: 'oauth#deauthorize'

  resources :nations

  resources :events
  get '/choose_site', to: 'events#choose_site'
  get '/choose_event', to: 'events#choose_event'
  get '/landing', to: 'events#landing'
  get '/set_event', to: 'events#set_event'

  get 'events/cancel_event', to: 'events#new_event'
  get 'events/cancel_site', to: 'events#new_site'

  get 'rsvps/cache', to: 'rsvps#cache'

  resources :rsvps
  post '/rsvps/check_in', to: 'rsvps#check_in'
  post '/rsvps/check_out', to: 'rsvps#check_out'
  get 'rsvps/new_guest', to: 'rsvps#new'
  get '/sync', to: 'rsvps#sync'
  post 'import_csv', to: 'rsvps#import_csv'

  resources :people

  resources :user_sessions

  resources :users do
    member do
      get :activate
      put :confirm
    end
  end

  get '/newsletter', to: 'users#newsletter'
  post '/send_newsletter', to: 'users#send_newsletter'

  resources :password_resets
  get 'reset', to: 'password_resets#password_reset'

  get 'admin', to: 'users#new'
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root 'rsvps#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  belongs_to :nation
  accepts_nested_attributes_for :nation

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }, unless: :skip_validation?
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }, unless: :skip_validation?
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }, unless: :skip_validation?

  validates :email, uniqueness: true

  before_create :setup_activation
  # after_create :send_activation_needed_email!

  attr_accessor :skip_validation

  def skip_validation?
    @skip_validation
  end

  def external?
    false
  end

  def resend_activation_email!
    send_activation_needed_email!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :same_user, only: %i[show edit update destroy]
  before_filter :is_admin, only: %i[show index new create destroy newsletter, send_newsletter]
  skip_before_filter :require_login, only: %i[new create activate confirm]
  http_basic_authenticate_with name: ENV['USERNAME'], password: ENV['PASSWORD'], only: %i[new create index show]

  # GET /users
  # GET /users.json
  def index
    redirect_to landing_path
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
    @nation = @user.build_nation
    @user.nation = @nation
  end

  # GET /users/1/edit
  def edit
    @page = 'settings'
    @nation = @user.nation
    render layout: false
  end

  def new_password
    @user = User.find(params[:id])
  end

  def change_password
    if @user.update(user_params)
      redirect_to nations_path, notice: 'Password was successfully updated!'
    else
      render :new_password
      flash[:error] = @user.errors
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.skip_validation = true

    if @user.save
      redirect_to login_path, notice: 'User was successfully created!'
    else
      render :new
      flash[:error] = @user.errors
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      @user.update_attributes(color: nil) if @user.color.nil? || @user.color.empty?
      @user.update_attributes(logo: nil) if @user.logo.nil? || @user.logo.empty?
      redirect_to admin_path, notice: 'User was successfully updated!'
    else
      render :edit
      flash[:error] = @user.errors
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @token = params[:id]
    else
      not_authenticated
    end
  end

  def confirm
    @token = params[:activation_token]
    if @user = User.load_from_activation_token(@token)
      if @user.update_attributes(user_params)
        @user.activate!
        redirect_to login_url, notice: 'Your account is now activated.'
      else
        render :activate
      end
    else
      not_authenticated
    end
  end

  def newsletter
  end

  def send_newsletter
    @body = params[:body]
    @subject = params[:subject]

    if params[:test]
      UserMailer.newsletter(User.find_by_email("alex@cstreet.ca"), @subject, @body).deliver
    else
      User.find_each do |user|
        UserMailer.newsletter(user, @subject, @body).deliver
      end
    end
    flash[:notice] = "Sending newsletter"
    redirect_to(newsletter_path)
  end

  private

  def is_admin
    redirect_to(:root, flash: { notice: "Page not found" }) unless ENV['ADMIN_ID'].include? current_user.id.to_s
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def same_user
    redirect_to root_path if current_user != @user && current_user.id != 1
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :active, :color, :logo, :nation_id, :nation_attributes => [:id, :name, :url, :client_uid, :secret_key])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Save", class: "btn btn-block" %>
<% end %>
<hr>
<div class="text-center">
  <%= link_to "Change Site & Event", landing_path, class: "btn btn-block" %>
</div>

app/views/users/activate.html.erb
<div class="container password-reset">

  <%= form_for @user, url: confirm_user_url(@user), method: :put do |f| %>
    <h3 class="check-title text-center">Please create a password</h3>

    <div class="field form-group">
      <%= f.email_field :email, class: "form-control text-center", placeholder:"Email Address", :readonly => true %>
      <%= f.password_field :password, class: "form-control text-center", placeholder:"Password" %>
      <%= f.password_field :password_confirmation, class: "form-control text-center", placeholder:"Password Confirmation" %>

    </div>
    <%= f.button "Save", class: "btn btn-block" %>

    <%= hidden_field_tag 'activation_token', @token %>
  <% end %>
</div>

app/views/users/edit.html.erb
<% @page = "settings" %>
<div class="user-settings">
  <div class="edit-user-header">
    <small>Account Settings</small>
  </div>
  <%= render 'form' %>
  <hr>
  <div class="support text-center" style="width:100%;margin:auto;">
    <%= link_to "Support", "https://cstreetcheck.zendesk.com/hc/en-us", target: "_blank" %>
  </div>
  <hr>
  <div class="logout">
    <%= link_to "Log out", logout_path %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="text-center new-user user-settings">

<h3 class="check-title">New user</h3>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control text-center" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control text-center" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control text-center" %>
  </div>
  <hr>
  <div class="edit-user-header">
    <p>Nation Settings</p>
  </div>
  <%= f.fields_for :nation, @user.build_nation do |n| %>
    <div class="form-group">
      <%= n.label :name, "Nation's Name" %>
      <%= n.text_field :name, class: "form-control text-center" %>
    </div>
    <div class="form-group">
      <%= n.label :url, "Nation's URL" %>
      <%= n.text_field :url, class: "form-control text-center" %>
    </div>
  <% end %>
  <hr>
  <%= f.submit "Save", class: "btn btn-block" %>
<% end %>
</div>

app/views/users/newsletter.html.erb
<div class="container newsletter">

  <%= form_tag 'send_newsletter', method: :post, class: "form-group" do %>
    <%= text_field_tag(
        :subject,
        params[:subject],
        placeholder: "Subject",
        class: "form-control"
    ) %>
    <%= text_area_tag(
        :body,
        params[:body],
        placeholder: "Body",
        class: "form-control"
    ) %>
    <%= label_tag "Send test email?" %>
    <%= check_box_tag(:test, params[:test],class: "form-control") %>
    <%= submit_tag "Send", class: "btn btn-primary form-control" %>
  <% end %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>