config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get '/callback', to: 'oauth#callback'
  get '/authorize', to: 'oauth#authorize'
  get '/deauthorize', to: 'oauth#deauthorize'

  resources :nations

  resources :events
  get '/choose_site', to: 'events#choose_site'
  get '/choose_event', to: 'events#choose_event'
  get '/landing', to: 'events#landing'
  get '/set_event', to: 'events#set_event'

  get 'events/cancel_event', to: 'events#new_event'
  get 'events/cancel_site', to: 'events#new_site'

  get 'rsvps/cache', to: 'rsvps#cache'

  resources :rsvps
  post '/rsvps/check_in', to: 'rsvps#check_in'
  post '/rsvps/check_out', to: 'rsvps#check_out'
  get 'rsvps/new_guest', to: 'rsvps#new'
  get '/sync', to: 'rsvps#sync'
  post 'import_csv', to: 'rsvps#import_csv'

  resources :people

  resources :user_sessions

  resources :users do
    member do
      get :activate
      put :confirm
    end
  end

  get '/newsletter', to: 'users#newsletter'
  post '/send_newsletter', to: 'users#send_newsletter'

  resources :password_resets
  get 'reset', to: 'password_resets#password_reset'

  get 'admin', to: 'users#new'
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root 'rsvps#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :rsvps
  belongs_to :nation, inverse_of: :events

  def self.import(nb, session_nation)
    event = find_or_create_by(
      nation_id: session_nation,
      eventNBID: nb['id'].to_i
    )

    event.update(
      name: nb['name'],
      start_time: nb['start_time'].to_datetime,
      end_time: nb['end_time'].to_datetime,
      time_zone: nb['time_zone']
    )

    event
  end

  def attended(rsvp)
    rsvps.where(host_id: rsvp.id, attended: true).count
  end

  def to_local_time
    start_time.in_time_zone(time_zone).strftime('%B %e, %Y at %l%P %Z')
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ApplicationHelper
  include EventsHelper

  before_filter :has_credential?

  def landing
    session[:current_site] = nil
    session[:current_event] = nil
  end

  def choose_site
    # if session[:current_site]
    #   session[:current_site] = nil
    #   session[:current_event] = nil
    # end

    begin
      response = token.get('/api/v1/sites', headers: standard_headers, params: { page: 1, per_page: 100, limit: 100 })
    rescue => ex
      @error = ex
    else
      @sites = JSON.parse(response.body)['results']
    end
    render layout: false
  end

  def choose_event
    session[:current_site] = params[:site] if params[:site]
    if session[:current_site]
      token_get_path = "/api/v1/sites/#{session[:current_site]}/pages/events"
      response = token.get(token_get_path, headers: standard_headers, params: { page: 1, per_page: 100, limit: 100, starting: 14.days.ago.to_s })
      parsed = JSON.parse(response.body)
      events = []
      if parsed['next']
        events << parsed['results']
        currentpage = 1
        is_next = parsed['next']
        while is_next
          currentpage += 1
          pagination_result = token.get(is_next, headers: standard_headers, params: { token_paginator: currentpage })
          response = JSON.parse(pagination_result.body)
          events << response['results']
          is_next = response['next']
        end

      elsif parsed['total_pages']
        current_page = 1
        total_pages = parsed['total_pages']
        events << parsed['results']
        while total_pages >= current_page
          current_page += 1
          response = token.get(token_get_path, headers: standard_headers, params: { page: current_page, per_page: 100, limit: 100, starting: 14.days.ago.to_s })
          events << JSON.parse(response.body)['results']
        end
      else
        events << parsed['results']
      end

      events.flatten!

      @current_events = Hash[events.select { |e| Time.zone = e['time_zone'] if e['start_time'] > 1.day.ago }.group_by { |e| e['start_time'].to_datetime.strftime('%B %Y') }.to_a.reverse]

      @past_events = Hash[events.select { |e| Time.zone = e['time_zone'] if e['start_time'] < 1.day.ago }.group_by { |e| e['start_time'].to_datetime.strftime('%B %Y') }.to_a.reverse]

    else
      redirect_to landing_path
    end
    render layout: false
  end

  def set_event
    if params[:event_id]
      token_get_path = "/api/v1/sites/#{session[:current_site]}/pages/events/#{params[:event_id]}"
      response = token.get(token_get_path, headers: standard_headers, params: { page: 1, per_page: 100, limit: 100 })
      event = JSON.parse(response.body)['event']

      token_put_path = "/api/v1/sites/#{session[:current_site]}/pages/events/#{params[:event_id]}"
      # puts clean_event_json(event)
      response = token.put(token_put_path, headers: standard_headers, body: clean_event_json(event))

      session[:current_event] = Event.import(event, current_user.nation.id).id
      @current_event = Event.find(session[:current_event])
      Rsvp.sync(@current_event, session[:current_site])

      redirect_to rsvps_path
    else
      redirect_to landing_path
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.rsvps.destroy_all
    @event.destroy
    session[:current_event] = nil
    redirect_to landing_path
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def new_site
    session[:current_site] = nil
    session[:current_event] = nil

    redirect_to controller: 'events', action: 'choose_site'
  end

  def new_event
    session[:current_event] = nil
    redirect_to controller: 'events', action: 'choose_event'
  end

  def venue_hash(event_from_nb)
    {}.tap do |v|
      v['name'] = event_from_nb['venue']['name']
      v['address'] = {
        'address1' => event_from_nb['venue']['address']['address1'],
        'address2' => event_from_nb['venue']['address']['address2'],
        'address3' => event_from_nb['venue']['address']['address3'],
        'city' => event_from_nb['venue']['address']['city'],
        'county' => event_from_nb['venue']['address']['county'],
        'state' => event_from_nb['venue']['address']['state'],
        'country_code' => event_from_nb['venue']['address']['country_code'],
        'zip' => event_from_nb['venue']['address']['zip'],
        'lat' => event_from_nb['venue']['address']['lat'],
        'lng' => event_from_nb['venue']['address']['lng'],
        'fips' => event_from_nb['venue']['address']['fips']
      }
    end
  end

  def event_hash(event_from_nb, venue)
    {
      'event' =>
      {
        'id' => event_from_nb['id'],
        'slug' => event_from_nb['slug'],
        'path' => event_from_nb['path'],
        'status' => 'published',
        'site_slug' => event_from_nb['site_slug'],
        'name' => event_from_nb['name'],
        'headline' => event_from_nb['headline'],
        'title' => event_from_nb['title'],
        'excerpt' => event_from_nb['excerpt'],
        'author_id' => event_from_nb['author_id'],
        'published_at' => event_from_nb['published_at'],
        'external_id' => event_from_nb['external_id'],
        'tags' => event_from_nb['tags'],
        'intro' => event_from_nb['intro'],
        'calendar_id' => event_from_nb['calendar_id'],
        'start_time' => event_from_nb['start_time'],
        'end_time' => event_from_nb['end_time'],
        'time_zone' => event_from_nb['time_zone'],
        'rsvp_form' => {
          'phone' => 'optional',
          'address' => 'optional',
          'allow_guests' => event_from_nb['rsvp_form']['allow_guests'],
          'accept_rsvps' => event_from_nb['rsvp_form']['accept_rsvps'],
          'gather_volunteers' => event_from_nb['rsvp_form']['gather_volunteers']
        },
        'capacity' => event_from_nb['capacity'],
        'show_guests' => event_from_nb['show_guests'],
        'venue' => venue,
        'autoresponse' => event_from_nb['autoresponse'],
        'shifts' => event_from_nb['shifts']
      }
    }
  end

  def clean_event_json(event_from_nb)
    venue = if event_from_nb['venue']['address']
              venue_hash(event_from_nb)
            else
              { 'name' => event_from_nb['venue']['name'] }
            end

    event_hash(event_from_nb, venue).to_json
  end
end

app/views/events/_landing.html.erb
<% if session[:current_site] %>
  <%= link_to choose_site_path do %>
    <div class="choose_site">
      <div class="word-wrapper">
        <%= session[:current_site].titleize %>
      </div>
      <i class="fa fa-angle-right" aria-hidden="true"></i>
    </div>
  <% end %>

<% else %>

  <%= link_to choose_site_path do %>
    <div class="choose_site">
      Select your website <i class="fa fa-angle-right" aria-hidden="true"></i>
    </div>
  <% end %>
<% end %>
<div class="sidebar-sites"></div>

<% if session[:current_event] %>

<%= link_to choose_event_path do %>
  <div class="choose_event">
    <div class="word-wrapper">
      <%= Event.find(session[:current_event]).name.titleize %>
    </div>
    <i class="fa fa-angle-right" aria-hidden="true"></i>
  </div>
<% end %>

<% else %>

  <%= link_to choose_event_path do %>
    <div class="choose_event">
      Select your event <i class="fa fa-angle-right" aria-hidden="true"></i>
    </div>
  <% end %>
<% end %>
<div class="sidebar-events"></div>

app/views/events/_print_event_groups.html.erb
<% event_group.each do |g| %>
  <div class="event-group">
    <h2 class="check-events"><%= g[0] %></h2>
    <% g[1].each do |e| %>
      <div class="event-block">
        <div class="event-info"><%= e['start_time'].to_datetime.strftime("%b %d")%></div>
        <%= link_to e["name"], set_event_path(event_id: e["id"]), method: :get %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/events/choose_event.html.erb
<% @page = "choose_event" %>
<div class="container events">

  <div class="current_events">
    <% if !@current_events.empty? %>
      <% @current_events.each do |month, event| %>
        <% event.each do |e| %>
            <%= link_to set_event_path(event_id: e["id"]), class: "list-item", method: :get do %>
              <div class="event">
                <div class="word-wrapper">
                  <%= e["name"] %>
                  <div class="event_date"><%= e["start_time"].to_datetime.to_formatted_s(:long) %></div>
                </div>
              </div>
            <% end %>
        <% end %>
      <% end %>
    <% else %>
      <div class="no-events text-center">
        <p>No upcoming events found.</p>
        <%= link_to("Select another site", landing_path) %>
      </div>
    <% end %>
  </div>

  <% if !@past_events.empty? %>
    <div class="past_events">
      <div class="list-separator">
        Past Events
      </div>
      <% @past_events.each do |month, event| %>
        <% event.each do |e| %>
          <% if event.class != String %>
            <%= link_to set_event_path(event_id: e["id"]), class: "list-item", method: :get do %>
              <div class="event">
                <div class="word-wrapper">
                  <%= e["name"] %>
                  <div class="event_date"><%= e["start_time"].to_datetime.to_formatted_s(:long) %></div>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/events/choose_site.html.erb
<div class="container choose-site">

  <% if @error %>
    <%= @error %>
  <% else %>

    <% @sites.each do |s| %>
      <%= link_to choose_event_path(:site => "#{s['slug']}"), method: :get, class: 'list-item black' do %>
        <div class="site">
          <div class="word-wrapper">
            <%= s['name'] %>
          </div>
        </div>
      <% end %>
    <% end %>

  <% end %>
</div>

app/views/events/landing.html.erb
<div class="container landing">

  <%= render "landing" %>

</div>