config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get '/callback', to: 'oauth#callback'
  get '/authorize', to: 'oauth#authorize'
  get '/deauthorize', to: 'oauth#deauthorize'

  resources :nations

  resources :events
  get '/choose_site', to: 'events#choose_site'
  get '/choose_event', to: 'events#choose_event'
  get '/landing', to: 'events#landing'
  get '/set_event', to: 'events#set_event'

  get 'events/cancel_event', to: 'events#new_event'
  get 'events/cancel_site', to: 'events#new_site'

  get 'rsvps/cache', to: 'rsvps#cache'

  resources :rsvps
  post '/rsvps/check_in', to: 'rsvps#check_in'
  post '/rsvps/check_out', to: 'rsvps#check_out'
  get 'rsvps/new_guest', to: 'rsvps#new'
  get '/sync', to: 'rsvps#sync'
  post 'import_csv', to: 'rsvps#import_csv'

  resources :people

  resources :user_sessions

  resources :users do
    member do
      get :activate
      put :confirm
    end
  end

  get '/newsletter', to: 'users#newsletter'
  post '/send_newsletter', to: 'users#send_newsletter'

  resources :password_resets
  get 'reset', to: 'password_resets#password_reset'

  get 'admin', to: 'users#new'
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root 'rsvps#index'
end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :event
  belongs_to :person

  has_many :guests, class_name: 'Rsvp', foreign_key: 'host_id'
  belongs_to :host, class_name: 'Rsvp'

  def self.search(search)
    where('name LIKE ?', "%#{search}%")
    where('email LIKE ?', "%#{search}%")
  end

  def self.sync(event, site)
    nation = event.nation
    nb_client = NationBuilder::Client.new(nation.name,
                                          nation.credentials.first.token, retries: 8)
    rsvps = NationBuilder::Paginator.new(nb_client, nb_client.call(
                                                      :events,
                                                      :rsvps,
                                                      site_slug: site,
                                                      id: event.eventNBID,
                                                      limit: 100
    ))
    unless rsvps.body['results'].empty?
      while rsvps
        rsvps.body['results'].each do |rsvp|
          person = Person.find_by(nation_id: nation.id, nbid: rsvp['person_id'])
          if person
            begin
              Resque.enqueue(UpdatePerson, person.id)
            rescue
              #if resque fails, just move on.
            end
          else
            nb_person = nb_client.call(:people,
                                       :show,
                                       id: rsvp['person_id'])
            person = Person.import(nb_person['person'], nation.id)
          end

          Rsvp.import(rsvp,
                      event.id,
                      person.id,
                      nation.id)
        end
        rsvps = (rsvps.next if rsvps.next?)
      end
    end
  end

  def self.letters(last_names)
    letters = last_names.map { |name| name[0].upcase.strip unless name.nil? || name.empty? }
    letters = letters.compact
    letters.sort! unless letters.empty? || letters.nil?
    letters = letters.uniq
  end

  def additional_status
    if canceled
      'Canceled'
    elsif volunteer
      'Volunteer'
    end
  end

  def ticket_name
    first_name = person.first_name
    last_name = person.last_name
    @name = if !first_name.empty? && !last_name.empty?
              "#{last_name}, #{first_name}"
            elsif !last_name.empty?
              last_name
            elsif !first_name.empty?
              first_name
            else
              'Guest'
            end
    @name.titleize
  end

  def self.import(r, e_id, p_id, n_id)
    rsvp = Rsvp.find_or_create_by(
      event_id: e_id,
      rsvpNBID: r['id'].to_i,
      person_id: p_id,
      nation_id: n_id
    )

    rsvp.assign_attributes(
      guests_count: r['guests_count'].to_i,
      canceled: r['canceled'],
      volunteer: r['volunteer'],
      shift_ids: r['shift_ids'].to_a,
      attended: r['attended']
    )

    rsvp.save if rsvp.changed?

    rsvp
  end

  def self.create_new_rsvp(nation, event, p_id)
    Rsvp.new(
      nation_id: nation,
      event_id: event,
      person_id: p_id,
      guests_count: 0,
      canceled: false,
      volunteer: false,
      shift_ids: [],
      attended: true
    )
  end

  def to_rsvp_object(person)
    rsvpObject = {
      'rsvp' => {
        'event_id' => event_id.to_i,
        'person_id' => person.nbid.to_i,
        'guests_count' => guests_count.to_i,
        'volunteer' => volunteer,
        'private' => is_private,
        'canceled' => canceled,
        'attended' => attended,
        'shift_ids' => shift_ids
      }
    }

    rsvpObject['rsvp']['id'] = rsvpNBID.to_i if rsvpNBID

    rsvpObject
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  include ApplicationHelper
  include RsvpsHelper
  include PeopleHelper

  before_filter :has_current_site_and_event
  before_filter :get_event
  before_filter :is_owner, only: [:show]

  def index
    if params[:query]
      @rsvps = Rsvp.includes(:person)
                   .where(event_id: @current_event.id, host_id: nil)
                   .where('lower(first_name) LIKE ? OR lower(last_name) LIKE ? OR lower(email) LIKE ?', "%#{params[:query].downcase}%", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%")
                   .order("people.last_name desc")
    else
      @rsvps = Rsvp.includes(:person)
                   .where(event_id: @current_event.id, host_id: nil)
                   .order("people.last_name desc")
    end

    @letters = Rsvp.letters(@rsvps.pluck("people.last_name"))
    render layout: false if params[:query]

  end

  def new
    @page = 'new-rsvp'
    @rsvp = Rsvp.new
    @person = Person.new
    @host = Rsvp.find(params[:host_id]) if params[:host_id]
    @event = if params[:event_id]
               Event.find(params[:event_id])
             else
               @current_event
             end
   render layout: false
  end

  def create
    @rsvp = Rsvp.new(rsvp_params)
    if @rsvp.save
      @person = Person.find_or_create_by(email: rsvp_params[:email], nation_id: @rsvp.nation_id)
      if @host && @event
        @rsvp.update_attributes(person_id: @person.id, nation_id: @current_event.nation_id, guests_count: 0, host_id: @host.id, event_id: @event.id)
      else
        @rsvp.update_attributes(person_id: @person.id, nation_id: @current_event.nation_id, guests_count: 0, event_id: @event.id  )
      end

    end
    redirect_to rsvps_path
  end

  def cache
    Resque.enqueue(Sync, params[:id], session[:current_site], session[:credential_id])

    respond_to do |format|
      format.json { render json: { status: 'started' } }
    end
  end

  def show
    @rsvp = Rsvp.find(params[:id])
    # check_nb_update(@rsvp.person)
    # @add_guests = add_guests(@rsvp)
    @guests = Rsvp.where(host_id: @rsvp.id)
    @guest_tickets = @current_event.rsvps.where(host_id: @rsvp.id)
    @attended_guest_tickets = @guest_tickets.where(attended: true)
    render layout: false
  end

  def check_in
    @rsvp = Rsvp.find(params[:id])
    @rsvp.update_attributes(attended: true)
    nationbuilder_rsvp = send_rsvp_to_nationbuilder(@rsvp, @rsvp.person)
    if nationbuilder_rsvp[:status]
      respond_to do |format|
        format.js {}
      end
    end
  end

  def check_out
    @rsvp = Rsvp.find(params[:id])
    @rsvp.update_attributes(attended: false)
    nationbuilder_rsvp = send_rsvp_to_nationbuilder(@rsvp, @rsvp.person)
    if nationbuilder_rsvp[:status]
      respond_to do |format|
        format.js {}
      end
    end
  end

  def sync
    Rsvp.sync(@current_event, session[:current_site])
    @rsvps = Rsvp.includes(:person).where(event_id: @current_event.id, host_id: nil).order("people.last_name desc")
    @letters = Rsvp.letters(@rsvps.pluck("people.last_name"))
    @rsvps.order('last_name DESC') unless @rsvps.empty?
    render layout: false
  end

  def import_csv
  end

  private

  def rsvp_params
    params.require(:rsvp).permit(:event_id, :guests_count, :canceled, :attended, :rsvpNBID, :nation_id, :volunteer, :is_private, :shift_ids, :host_id, :person_id, :ticket_type, :tickets_sold, :person, person_attributes: %i[first_name last_name email phone_number])
  end

  def has_current_site_and_event
    if session[:current_site] && session[:current_event] then true else redirect_to landing_path end
  end

  def is_owner
    if current_user.nation.id != Rsvp.find(params[:id]).person.nation_id
      begin
        redirect_to(:back, flash: { error: "Page not found" })
      rescue ActionController::RedirectBackError
        redirect_to(:root, flash: { error: "Page not found" })
      end
    end
  end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper

  def send_rsvp_to_nationbuilder(rsvp, person)
    # return {status: true, id: 10000000}
    rsvpObject = rsvp.to_rsvp_object(person)
    if rsvpObject['rsvp'].key?('id')
      begin
        checkInResponse = token.put("/api/v1/sites/#{session[:current_site]}/pages/events/#{@current_event.eventNBID}/rsvps/#{rsvp.rsvpNBID}", headers: standard_headers, body: rsvpObject.to_json)
        checked_in = JSON.parse(checkInResponse.body)['rsvp']
      rescue => ex
        validation_errors(ex)
        # begin
        #   nb_error = JSON.parse(ex.response.body)
        #   error = nb_error['message']
        #   if nb_error['validation_errors']
        #     error += '<ul>'
        #     for v_error in nb_error['validation_errors']
        #       error = error + '<li>' + v_error + '</li>'
        #     end
        #     error += '</ul>'
        #   end
        # rescue JSON::ParserError => e
        #   error = 'Nationbuilder unresponsive, please try again'
        # end
        # return { status: false, error: error }
      else
        return { status: true, id: checked_in['id'].to_i }
      end

    else

      begin
        checkInResponse = token.post("/api/v1/sites/#{session[:current_site]}/pages/events/#{@current_event.eventNBID}/rsvps/", headers: standard_headers, body: rsvpObject.to_json)
      rescue => ex
        validation_errors(ex)
        # begin
        #   nb_error = JSON.parse(ex.response.body)
        #   error = nb_error['message']
        #   if nb_error['validation_errors']
        #     error += '<ul>'
        #     for v_error in nb_error['validation_errors']
        #       error = error + '<li>' + v_error + '</li>'
        #     end
        #     error += '</ul>'
        #   end
        # rescue JSON::ParserError => e
        #   error = 'Nationbuilder unresponsive, please try again'
        # end
        # return { status: false, error: error }
      else
        checked_in = JSON.parse(checkInResponse.body)['rsvp']
        return { status: true, id: checked_in['id'].to_i }
      end

    end
  end

  def validation_errors(ex)
    begin
      nb_error = JSON.parse(ex.response.body)
      error = nb_error['message']
      if nb_error['validation_errors']
        error += '<ul>'
        for v_error in nb_error['validation_errors']
          error = error + '<li>' + v_error + '</li>'
        end
        error += '</ul>'
      end
    rescue JSON::ParserError => e
      error = 'Nationbuilder unresponsive, please try again'
    end
    return { status: false, error: error }
  end

  def get_count
    rsvps = @current_event.rsvps
    @total = rsvps.select { |r| r unless r.host_id }.count
    rsvps.each do |r|
      @total += r.guests_count
    end

    @attending = rsvps.select { |r| r if r.attended }.count
  end

  def add_guests(rsvp)
    if rsvp.guests.count >= rsvp.guests_count
      false
    else
      true
    end
  end

  def get_rsvps
    response = token.get("/api/v1/sites/#{session[:current_site]}/pages/events/#{@current_event.eventNBID}/rsvps/", params: { per_page: 100, limit: 100 }, headers: standard_headers)
    parsed = JSON.parse(response.body)
    rsvpListfromNB = []

    # This is due to different pagination rules implemented by NationBuilder

    if parsed['next']
      rsvpListfromNB << parsed['results']
      currentpage = 1
      is_next = parsed['next']
      while is_next
        currentpage += 1
        pagination_result = token.get(is_next, headers: standard_headers, params: { token_paginator: currentpage, per_page: 100, limit: 100 })
        response = JSON.parse(pagination_result.body)
        rsvpListfromNB << response['results']
        is_next = response['next']
      end

    elsif parsed['total_pages']
      current_page = 1
      total_pages = parsed['total_pages']
      rsvpListfromNB << parsed['results']
      while total_pages >= current_page
        current_page += 1
        response = token.get("/api/v1/sites/#{session[:current_site]}/pages/events/#{@current_event.eventNBID}/rsvps/", headers: standard_headers, params: { page: current_page, per_page: 100, limit: 100 })
        rsvpListfromNB << JSON.parse(response.body)['results']
      end
    else
      rsvpListfromNB << parsed['results']
    end

    rsvpListfromNB.flatten!
  end

  def check_sync
    get_rsvps
  end
end

app/views/rsvps/_check.html.erb
<% if !rsvp.attended %>
 <%= link_to("#", class: "checkin", data: {id: rsvp.id}, :method => "post", remote: true) do %>
    <%= image_tag(asset_path("Icon/Checkmark/Grey.svg", class: "check") %>
  <% end %>
<% else %>
  <%= link_to("#", class: "checkout", data: {id: rsvp.id}, :method => "post", remote: true) do %>
    <%= image_tag(asset_path("Icon/Checkmark/Color.svg", class: "check") %>
  <% end %>
<% end %>

app/views/rsvps/_loading.html.erb
<div class="loader-wrap <%= status %>" id="load-<%=id%>">
    <div class="loader" id="loader">
      <div class="loader-animation" style="display: none;" id="load-ani-<%=id%>"></div>
      <div class="checkmark"></div>
    </div>
</div>

app/views/rsvps/_new_rsvp.html.erb
<div class="add-rsvp">
<div class="show-card-close"><%= image_tag(asset_path("X.svg")) %></div>

  <div class="add-rsvp-header">
    <small>Add RSVP</small>
  </div>
  <div class="add-rsvp-form">

    <%= form_for @person do |p| %>
      <!-- <%= p.nested_fields_for :rsvps do |r| %> -->
      <%= hidden_field_tag :host_id, @host.id if @host %>
      <%= hidden_field_tag :event_id, @event.id %>
      <!-- <% end %> -->
      <div class="form-group">
      <%= p.label :first_name %>
      <%= p.text_field :first_name %>
      </div>
      <div class="form-group">
      <%= p.label :last_name %>
      <%= p.text_field :last_name %>
      </div>
      <div class="form-group">
      <%= p.label :email %>
      <%= p.text_field :email %>
      </div>
      <div class="form-group">
      <%= p.label :phone_number %>
      <%= p.text_field :phone_number %>
      </div>
      <div class="additional-fields-toggle">
        <p>Additional Fields <i class="fa fa-angle-down" aria-hidden="true"></i></p>
      </div>
      <div class="additional-fields" style="display: none;">
        <div class="form-group">
        <%= p.label :home_zip %>
        <%= p.text_field :home_zip %>
        </div>
      </div>
      <%= p.submit "Save", class: "btn btn-block" %>
    <% end %>

    <div class="import_csv text-center form-group">
      <label class="import_csv_label">
        Import CSV <input type="file" id="csv_input" hidden>
      </label>
    </div>
  </div>

</div>

app/views/rsvps/_rsvp.html.erb
<% if !rsvp.canceled %>
  <% if !rsvp.attended %>
   <%= link_to("#", class: "checkin check", id: "rsvp_#{rsvp.id}", data: {id: rsvp.id}, :method => "post", remote: true) do %>
      <%= render 'loading', id: rsvp.id, status: "checked-out" %>
    <% end %>
  <% else %>
    <%= link_to("#", class: "checkout check", id: "rsvp_#{rsvp.id}", data: {id: rsvp.id}, :method => "post", remote: true) do %>
      <%= render 'loading', id: rsvp.id, status: "checked-in" %>
    <% end %>
  <% end %>
<% end %>

app/views/rsvps/_rsvp_list.html.erb
<% @letters = letters %><% @rsvps = rsvps %>
<% @letters.each do |letter| %>
  <div class="list-separator">
    <%= letter %>
  </div>
  <% @rsvps.each do |rsvp| %>
    <% if rsvp.person && rsvp.person.last_name[0].upcase == letter %>
    <!-- Cancelled or not? -->
    <% if rsvp.canceled %>
      <div class='rsvp canceled list-item'>
    <% else %>
      <div class='rsvp list-item'>
    <% end %>
    <a href="<%= rsvp_path(rsvp) %>" class="rsvp-click-zone"></a>

      <!-- Guest Dots -->
      <% if rsvp.guests_count > 0 && !rsvp.canceled %>
        <div class="guest-dots">
          <% attended = @current_event.attended(rsvp) %>

          <% attended.times do %>
            <%= image_tag(asset_path("Oval Color.svg"), class: "guest-oval guest-oval-checked") %>
          <% end %>

          <% (rsvp.guests_count - attended).times do %>
            <%= image_tag(asset_path("Oval.svg"), class: "guest-oval") %>
          <% end %>

        </div>
      <% end %>

      <!-- RSVP ticket name -->
      <%= rsvp.ticket_name %>

      <!-- Render the RSVP checkmark -->
      <%= render 'rsvp', rsvp: rsvp %>

      <!-- RSVP Canceled or Volunteer -->
      <small><%= rsvp.additional_status %></small>

    </div>

    <% end %>
  <% end %>
<% end %>

app/views/rsvps/_rsvp_show.html.erb
<div class=" rsvp-show">
  <div class="rsvp-person">

      <small><%= @rsvp.additional_status %></small>
    <h3>
      <%= @rsvp.person.full_name %>
      <%= render 'rsvp', rsvp: @rsvp %>
    </h3>

    <div class="email">
      <small>Email</small>
      <h3>
        <%= if @rsvp.person.email then @rsvp.person.email else "N/A" end %>
      </h3>
    </div>

    <div class="tickets host-tickets">
      <%= render "ticket", rsvp: @rsvp %>
    </div>
  </div>

  <% if @rsvp.guests_count > 0 && !@rsvp.canceled %>
    <div class="guests">
      <div class="list-separator">
        <small style="color:#7C7C7C">GUESTS</small>

        <% (@rsvp.guests_count - @attended_guest_tickets.count).times do %>
          <%= image_tag(asset_path("Oval.svg"), class: "guest-oval") %>
        <% end %>

        <% @attended_guest_tickets.each do %>
          <%= image_tag(asset_path("Oval Color.svg"), class: "guest-oval guest-oval-checked") %>
        <% end %>

      </div>

      <div class="tickets">
        <% @guest_tickets.each do |rsvp| %>
          <% @rsvp = rsvp %>
          <%= link_to rsvp_path(@rsvp) do %>
            <%= render "ticket" %>
          <% end %>
        <% end %>

        <% @rsvp = Rsvp.find(params[:id]) %>
        <% @i = 1 %>
        <% (@rsvp.guests_count - @guest_tickets.count).times do %>
          <%= link_to(new_rsvp_path + "?event_id=#{@rsvp.event.id.to_s}&host_id=#{@rsvp.id.to_s}", class: "new-ticket") do %>
            <%= render "ticket" %>
          <% end %>
          <% @i += 1 %>
        <% end %>
      </div>
    </div>
  <% end %>

</div>

app/views/rsvps/_search.html.erb
<% if @page == "index" %>
  <div class="search">
    <input type="text" name="query" id="search" placeholder="Search by name or email...">
      <i class="fa fa-search" aria-hidden="true"></i>
    </input>
  </div>
<% end %>

app/views/rsvps/_ticket.html.erb
<% if !@i %>

  <% if @rsvp.canceled %>
    <div class="ticket ticket-canceled" id="ticket-<%= @rsvp.id %>" data-id="<%= @rsvp.id %>">
  <% elsif @rsvp.attended %>
    <div class="ticket ticket-checked" id="ticket-<%= @rsvp.id %>" data-id="<%= @rsvp.id %>">
  <% else %>
    <div class="ticket" id="ticket-<%= @rsvp.id %>" data-id="<%= @rsvp.id %>">
  <% end %>

      <div class="left-circle-cover circle-cover"></div>
      <div class="circle left-circle"></div>

      <div class="ticket-name">
        <%= @rsvp.person.full_name %>'s Ticket
      </div>

      <div class="circle right-circle"></div>
      <div class="right-circle-cover circle-cover"></div>
    </div>

<% elsif @rsvp.host_id %>

    <div class="ticket">
      <div class="left-circle-cover circle-cover"></div>
      <div class="circle left-circle"></div>
      <div class="ticket-name">
        <%= @rsvp.person.full_name %>'s Ticket
      </div>
      <div class="circle right-circle"></div>
      <div class="right-circle-cover circle-cover"></div>
    </div>

<% elsif !@rsvp.canceled %>

    <div class="ticket">
      <div class="left-circle-cover circle-cover"></div>
      <div class="circle left-circle"></div>

      <div class="ticket-name">
        Guest #<%= @i %>
      </div>

      <div class="circle right-circle"></div>
      <div class="right-circle-cover circle-cover"></div>
    </div>

<% end %>

app/views/rsvps/check_in.js.erb
// $("#rsvp_<%= @rsvp.id %>").replaceWith("<%= escape_javascript(render 'rsvps/rsvp', rsvp: @rsvp) %>");

$.each($('.check'), function(index, value){
  if (value.id === "rsvp_<%= @rsvp.id %>") {
    $(value).replaceWith("<%= escape_javascript(render 'rsvps/rsvp', rsvp: @rsvp) %>");
  }
})


$("#ticket-<%= @rsvp.id %>").addClass("ticket-checked");
$('.loader-animation').hide();
$("#load-<%= @rsvp.id %>").removeClass("checked-out");

app/views/rsvps/check_out.js.erb
// $("#rsvp_<%= @rsvp.id %>").replaceWith("<%= escape_javascript(render 'rsvp', rsvp: @rsvp) %>");

$.each($('.check'), function(index, value){
  if (value.id === "rsvp_<%= @rsvp.id %>") {
    $(value).replaceWith("<%= escape_javascript(render 'rsvps/rsvp', rsvp: @rsvp) %>");
  }
})


$("#ticket-<%= @rsvp.id %>").removeClass("ticket-checked");
$('.loader-animation').hide();
$("#load-<%= @rsvp.id %>").addClass("checked-out");

app/views/rsvps/index.html.erb
<% @page = "index" %>
<div class="container rsvps">
  <div id="rsvp-results">
    <%= render "rsvp_list", letters: @letters, rsvps: @rsvps %>
  </div>
  <div class="show-card" style="display: none;">
    <div class="show-card-content"></div>
  </div>
  <% if @rsvps.empty? %>
  <div class="no-rsvps text-center">
    <p>No RSVPs found.</p>
    <%= link_to("Select another event", landing_path) %>
  </div>  
  <% end %>
</div>

app/views/rsvps/new.html.erb
<%= render 'new_rsvp' %>

app/views/rsvps/sync.html.erb
<%= render "rsvp_list", letters: @letters, rsvps: @rsvps %>

app/views/rsvps/sync.js.erb
location.reload();