config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get '/callback', to: 'oauth#callback'
  get '/authorize', to: 'oauth#authorize'
  get '/deauthorize', to: 'oauth#deauthorize'

  resources :nations

  resources :events
  get '/choose_site', to: 'events#choose_site'
  get '/choose_event', to: 'events#choose_event'
  get '/landing', to: 'events#landing'
  get '/set_event', to: 'events#set_event'

  get 'events/cancel_event', to: 'events#new_event'
  get 'events/cancel_site', to: 'events#new_site'

  get 'rsvps/cache', to: 'rsvps#cache'

  resources :rsvps
  post '/rsvps/check_in', to: 'rsvps#check_in'
  post '/rsvps/check_out', to: 'rsvps#check_out'
  get 'rsvps/new_guest', to: 'rsvps#new'
  get '/sync', to: 'rsvps#sync'
  post 'import_csv', to: 'rsvps#import_csv'

  resources :people

  resources :user_sessions

  resources :users do
    member do
      get :activate
      put :confirm
    end
  end

  get '/newsletter', to: 'users#newsletter'
  post '/send_newsletter', to: 'users#send_newsletter'

  resources :password_resets
  get 'reset', to: 'password_resets#password_reset'

  get 'admin', to: 'users#new'
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  root 'rsvps#index'
end

app/views/layouts/_check_sync.html.erb
<div class="container loading" style="display: none;">
  <div class="logo">
    <% if current_user && current_user.nation.name.include?("columbia") %>
      <%= image_tag(asset_path("logo_caa.svg")) %>
    <% else %>
      <%= image_tag(asset_path("logo.svg")) %>
    <% end %>

  </div>
  <div class="loading-quote">
    <p>“Politics hates a vacuum. If it isn't filled with hope, someone will fill it with fear.”</p>
    <small class="name">Naomi Klein</small>
  </div>
</div>

app/views/layouts/_loading.html.erb
<style>

.loader-wrap{
  width: 27px;
  height: 27px;
  background-image: linear-gradient(-225deg, #3A7BD5 0%, #1CA8EB 51%, #00D2FF 100%);
  border-radius: 100%;
  margin-top: 100px;
  margin-left: 100px;
  text-align: center;
}

.loader{
  width: 85.185%;
  height: 85.185%;
  background: white;
  border-radius: 50%;
  position: relative;
  top: 7.407%;
  left: 7.407%;
}

/* LOADER 1 */

#loader-1:before, #loader-1:after{
  content: "";
  position: absolute;
  width: 100%;
  height: 100%;
  border-radius: 100%;
  border: 5px solid transparent;
  border-top-color: #fff;
  width: 126.11%;
  height: 126.11%;
  left: -14%;
  top: -14%;
}

#loader-1:before{
  z-index: 100;
  animation: spin 1s infinite;
}

#loader-1:after{
  border: 2px solid transparent;
}

@keyframes spin{
  0%{
    -webkit-transform: rotate(0deg);
    -ms-transform: rotate(0deg);
    -o-transform: rotate(0deg);
    transform: rotate(0deg);
  }

  100%{
    -webkit-transform: rotate(360deg);
    -ms-transform: rotate(360deg);
    -o-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}

.checkmark{
  display: block;
  position: relative;
  width: 37.037%;
  height: 51.85%;
  background-image: linear-gradient(-225deg, #3A7BD5 0%, #1CA8EB 51%, #00D2FF 100%);
  z-index: 99999;
  transform: rotate(45deg);
  left: 30%;
  top: 20%;
}
.checkmark:after{
    content: '';
    display: block;
    position: absolute;
    z-index: 99999;
    width: 70%;
    height: 80%;
    background: white;
  }
}
</style>

<div class="loader-wrap">
  <div class="loader" id="loader-1">
    <div class="checkmark"></div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="container sidebar">

  <% if !current_user %>
    <div class="sidebar-header"></div>
    <div class="sidebar-filler1 sidebar-filler"></div>
    <div class="sidebar-filler2 sidebar-filler"></div>
  <% end %>

  <% if current_user %>
      <% if current_user.nation.name.include?("columbia") %>
      <div class="sidebar-header logged-in" style="background-image: linear-gradient(37deg, #6AABDC 37%, #A3D5F0 100%)" >
        <%= link_to(image_tag(asset_path("logo_caa.svg"), class: "desktop-logo"), root_path) %>
      <% else %>
      <div class="sidebar-header logged-in" style="background-image:linear-gradient(13deg, #65CCEE 0%, #9DAAD7 100%);" >
        <%= link_to(image_tag(asset_path("logo.svg"), class: "desktop-logo"), root_path) %>
      <% end %>
      <div class="refresh">
        <%= link_to(image_tag(asset_path("Icon/Refresh/White.svg")), "#") %>
        <small>Refresh</small>
      </div>
    </div>
    <div class="sidebar-main">
      <%= render 'events/landing' %>
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <title><%= content_for?(:title) ? yield(:title) : "Check by cStreet" %></title>
    <%= favicon_link_tag %>
    <%= favicon_link_tag 'mb-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>

    <%= stylesheet_link_tag  "application"  %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "papaparse.min" %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="body">
      <% unless @noheader %>
        <% if current_user && current_user.nation.name.include?("columbia") %>
          <header style="background-image: linear-gradient(20deg, #6AABDC 37%, #A3D5F0 100%)">
        <% else %>
          <header style="background-image: linear-gradient(20deg, #65CCEE 37%, #9DAAD7 100%)">
        <% end %>
          <%= link_to landing_path do %>
          <% if current_user && current_user.nation.name.include?("columbia") %>
            <%= image_tag(asset_path("logo_caa.svg")) %>
          <% else %>
            <%= image_tag(asset_path("logo.svg")) %>
          <% end %>
            <% if @current_event %>
            <div class="current-event">
              <p>
                <% if @current_event.name.length > 30 %>
                  <%= @current_event.name[0..30] + "..." %>
                <% else %>
                  <%= @current_event.name %>
                <% end %>
              </p>
              <small><%= @current_event.start_time.to_formatted_s(:long) %></small>
            </div>
          <% end %>
            <% if @page == "index" %>
              <div class="refresh">
                <%= link_to(image_tag(asset_path("Icon/Refresh/White.svg")), "#") %>
                <small>Refresh</small>
              </div>
            <% elsif @page == "choose_event" %>
            <div class="refresh_events">
              <%= link_to(image_tag(asset_path("Icon/Refresh/White.svg")), "#") %>
              <small>Refresh</small>
            </div>
            <% end %>
          <% end %>
        </header>
      <% end %>
      <%= render 'layouts/sidebar' %>
      <div class="main">
        <%= render 'rsvps/search' %>
        <%= render 'layouts/check_sync' %>
        <%= yield %>
      </div>
      <% unless @nofooter || !current_user %>
        <footer>
          <div class="icons">
            <% if session[:current_event] && session[:current_site] %>
              <div class="check-in">
                <%= link_to rsvps_path do %>
                  <% if @page != "index" %>
                    <%= image_tag(asset_path("Icon/Checkmark/Grey.svg")) %>
                    <h6>Check In</h6>
                  <% else %>
                    <%= image_tag(asset_path("Icon/Checkmark/Color.svg")) if @page == "index" %>
                    <h6 style="color: #0AC4F8">Check In</h6>
                  <% end %>
                <% end %>
              </div>
              <div class="add-rsvp-btn">
                <% if @page != "new-rsvp" %>
                  <%= link_to new_rsvp_path do %>
                    <%= image_tag(asset_path("Icon/Add/Grey.svg")) %>
                    <h6>Add RSVP</h6>
                  <% end %>
                <% else %>
                <%= link_to new_rsvp_path do %>
                  <%= image_tag(asset_path("Icon/Add/Color.svg")) %>
                  <h6 style="color: #0AC4F8">Add RSVP</h6>
                <% end %>
                <% end %>
              </div>
            <% end %>
            <div class="settings">
              <% if @page != "settings" %>
                <%= link_to edit_user_path(current_user) do %>
                  <%= image_tag(asset_path("Icon/Gear/Grey.svg")) %>
                  <h6>Settings</h6>
                <% end %>
              <% else %>
              <%= link_to edit_user_path(current_user) do %>
                <%= image_tag(asset_path("Icon/Gear/Color.svg")) %>
                <h6 style="color: #0AC4F8">Settings</h6>
              <% end %>
              <% end %>
            </div>
          </div>
        </footer>
      <% end %>
    </div>
  </body>
</html>

app/views/layouts/user_mailer.html.erb
<!-- Inliner Build Version 4380b7741bb759d6cb997545f3add21ad48f010b -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;">
  <head>
    <!-- If you delete this tag, the sky will fall on your head -->
    <meta name="viewport" content="width=device-width"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Check by cStreet Campaigns</title>
  </head>
  <body bgcolor="#F0F0F0" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; margin: 0; padding: 0;">
    <style type="text/css">
      @media only screen and (max-width: 600px) {
        a[class="btn"] {
          display: block !important;
          margin-bottom: 10px !important;
          background-image: none !important;
          margin-right: 0 !important;
        }
        div[class="column"] {
          width: auto !important;
          float: none !important;
        }
        table.social div[class="column"] {
          width: auto !important;
        }
      }
    </style>
    <!-- BODY -->
    <%= yield %>
    <!-- /BODY -->
    <!-- FOOTER -->
    <table class="footer-wrap" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; width: 100%; clear: both !important; margin: 0; padding: 0;">
      <tr style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;">
        <td class="container" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; display: block !important; max-width: 560px !important; clear: both !important; margin: 0 auto; padding: 0;">

          <!-- content -->
          <div class="content" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; max-width: 600px; display: block; margin: 0 auto; padding: 15px;">
            <table style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; width: 100%; margin: 0; padding: 0;">
              <tr style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;">

                <td align="center" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;">
                  <a href="http://www.cstreet.ca/" target="_blank"><img style="display:inline;max-width: 45px; margin: 10px 0; padding: 0;" src="<%= asset_url("cstreetlogo.png") %>"/></a>
                  <p style="color: #999999; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-weight: normal; font-size: 14px; line-height: 1.6; margin: 0 0 10px; padding: 0;">
                    You were sent this email because it was requested from cStreet's Check app. If you did not request this email please contact
                    <a href="mailto:check@cstreet.ca" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; color: #127DB3; text-decoration: underline;">check@cstreet.ca</a>.
                  </p>
                </td>
              </tr>
            </table>
          </div>
          <!-- /content -->

        </td>
        <td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; margin: 0; padding: 0;"></td>
      </tr>
    </table>
    <!-- /FOOTER -->
  </body>
</html>

app/views/layouts/user_mailer.text.erb
<%= yield %>

----

You were sent this email from cStreet's Check app. If you did not request this email please contact check@cstreet.ca.